#!/usr/bin/with-contenv bash

# `flexget daemon` runs all tasks in the config every hour by default, for more
# options see https://flexget.com/Plugins/Daemon/scheduler.
#
# `--autoreload-config` reloads the config *before* running the tasks, not
# when the configuration actually changes.
#

if [ -f /config/.config-lock ]; then
    rm /config/.config-lock
fi

s6-setuidgid abc /usr/local/bin/flexget \
    -c "/config/config.yml" \
    --logfile "${FLEXGET_LOG_FILE:-flexget.log}" \
    --loglevel "${FLEXGET_LOG_LEVEL:-info}" \
    daemon start --autoreload-config
